### ISSUE TITLE
Rounding bug in modp_dtoa2

### ISSUE THREAD

**Issue by gka** [jeroenooms/jsonlite#148] opened 2016-09-20 20:56 UTC
This is unexpected behavior:

```R
> toJSON(0.9995)
[0.9995] 
> toJSON(0.99995)
[0.1] 
```

I see that the default for the `digits` parameter is 4 (should be higher!), but even if it cuts of after 4 digits I would expect this

```R
> toJSON(0.99995)
[0.9999] 
```

**Comment by jonocarroll** [comment] 2016-09-20 22:28
Bug traces back through `asJSON` and can be reproduced with 

``` r
jsonlite:::asJSON(0.99995, digits=4)
#> [1] "[0.1]"
```
which itself traces back through `num_to_char`

``` r
jsonlite:::num_to_char(0.99995, digits=4)
#> [1] "0.1"
```
but after that it's tracing back through `num_to_char.c` which I'll leave to someone more qualified.

**Comment by gka** [comment] 2016-09-20 22:54
then how about at least set digit default to something higher, i.e. 10. ?

**Comment by gka** [comment] 2016-09-20 22:56
and/or work around the bug by rounding numbers to make sure they never have more digits than the digit parameters supports

**Comment by naehrstoff** [comment] 2016-09-21 08:51
Could this be due to the call to `modp_dtoa2` on [line 61](https://github.com/jeroenooms/jsonlite/blob/master/src/num_to_char.c#L61)? They have this similar issue: https://github.com/client9/stringencoders/issues/40

**Comment by jeroenooms** [comment] 2016-09-21 09:05
Wow that's a big bug. How did this not get noticed? Seems to be in `modp_dtoa2` in deed. You can avoid it via `use_signif=TRUE` 

```
jsonlite:::asJSON(0.99995, digits=9, use_signif=T)
```

**Comment by jeroenooms** [comment] 2016-09-23 20:03
Fixed @ https://github.com/jeroenooms/jsonlite/commit/c0a9a572bc78a2307f5e5e30ba27eae60293077b. This problem has been addressed by @client9 in the upstream stringencoder library.

**Closed by jeroenooms** 2016-09-23 20:03 UTC
